function y = f1(x)
%F1 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 18-Apr-2015 03:12:45

persistent Hd;

if isempty(Hd)
    
    % IIR Comb Notching filter designed using the IIRCOMB function.
    
    % All frequency values are in Hz.
    Fs = 1500;  % Sampling Frequency
    
    N     = 10;  % Order
    Q     = 10;  % Q-factor
    Apass = 1;   % Bandwidth Attenuation
    
    BW = 2*Fs/2/10/Q;
    
    % Calculate the coefficients using the IIRCOMB function.
    [b, a] = iircomb(N, BW/(Fs/2), Apass);Hd = dsp.IIRFilter( ...
        'Structure', 'Direct form II', ...
        'Numerator', b, ...
        'Denominator', a);
end

y = step(Hd,x);


% [EOF]
